### ISSUE TITLE
How to target different architectures?

### ISSUE THREAD

**Issue by david99999** [Affectiva/android-sdk-samples#23]
Hi, thanks for your aweasome SDK, I've been playing around with it and found that once the apk is built it only contains the native library for armeabi-v7 architecture
![affectiva](https://user-images.githubusercontent.com/4248801/29746896-d4b65250-8aae-11e7-8087-3a1170d75462.png)
does it mean that if we use this SDK we are going to be only targeting users with only this type of phones?
Thanks again for your great SDK

**Comment by adennie** [comment]
Hi, yes, currently only the armeabi-v7 architecture is supported.
