### ISSUE TITLE
sdk expired issue?

### ISSUE THREAD

**Issue by xhzzhang** [Affectiva/android-sdk-samples#24]
Hello everyone, i have download android sample SDK, and tested it works well, but i have question to ask, Is SDK will expired after 60 days later?
Is someone can reply me? thanks

**Comment by adennie** [comment]
Hi, would you mind asking this question at http://discuss.affectiva.com/c/emotion-sdk?  We like to keep this issue tracker focused on the contents of this repo (i.e. the samples).  Thanks.
